#!/bin/bash

wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-SemiboldIt-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-SemiboldIt-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-SemiboldIt-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-SemiboldIt-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Bold-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Bold-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Bold-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Bold-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BoldIt-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BoldIt-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BoldIt-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BoldIt-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Black-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Black-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Black-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Black-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BlackIt-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BlackIt-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BlackIt-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-BlackIt-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLight-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLight-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLight-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLight-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLightIt-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLightIt-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLightIt-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-ExtraLightIt-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Light-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Light-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Light-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Light-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-LightIt-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-LightIt-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-LightIt-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-LightIt-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Regular-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Regular-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Regular-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Regular-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-It-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-It-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-It-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-It-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-It-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Semibold-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Semibold-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Semibold-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Semibold-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/SourceSansPro-Semibold-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-regular-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-regular-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-regular-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-regular-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-regular-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-italic-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-italic-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-italic-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-italic-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-italic-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-bolditalic-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-bolditalic-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-bolditalic-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-bolditalic-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/texgyreadventor-bolditalic-webfont.svg
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/modernpics-webfont.eot
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/modernpics-webfont.woff
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/modernpics-webfont.ttf
wget https://repositories.tdl.org/uh-ir/themes/UH/fonts/modernpics-webfont.svg